version: '3'

networks:
  default:
    external:
      name: nginx-proxy

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "80"
    environment:
      VIRTUAL_HOST: irabu.co.tz
      LETSENCRYPT_HOST: irabu.co.tz
      LETSENCRYPT_EMAIL: info@irabu.co.tz
    networks:
      - default
