version: '3'

networks:
  default:
    external:
      name: nginx-proxy

services:
  website:
    build: .
    ports:
      - "80:80"
    environment:
      VIRTUAL_HOST: irabu.dev
      LETSENCRYPT_HOST: irabu.dev
      LETSENCRYPT_EMAIL: info@irabu.co.tz
    networks:
      - default
